### ISSUE TITLE
Create slash command for assigning roles

### ISSUE THREAD

**Issue by ElijahMSmith** [KnightHacks/Lancelot-Mini#2]
When the user types `/roles assign`, they should receive a message from the bot (not ephemeral so that other individuals can use it as well) with a menu the user can use to select one or more roles. For this issue, we just need the bot to respond with a dummy menu when the command is run.

Consider looking into Select Menu: https://discordjs.guide/interactions/select-menus.html#responding-to-select-menus

**Comment by Joaqstarr** [comment]
I can give this a shot

**Comment by Joaqstarr** [comment]
https://github.com/Joaqstarr/Lancelot.git
